kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: t6vz+7LEAynzbtWulPtCiKl5Sv3L6wEXApSoe+BDjo4=
      - identity: {}
