---
  - name: Deploy CoreDNS
    hosts: control_plane[0]
    tasks:
      - name: Deploy CoreDNS from yaml description
        command: kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns-1.7.0.yaml