---
  - name: distribute worker configs
    hosts: workers
    tasks:
      - name: copy kubelet config
        copy:
          src: "{{ playbook_dir }}/../../../configs/{{ hostname }}.kubeconfig"
          dest: "~"
      - name: copy kube proxy config
        copy:
          src: "{{ playbook_dir }}/../../../configs/kube-proxy.kubeconfig"
          dest: "~"

  - name: distribute control plane configs
    hosts: control_plane
    tasks:
      - name: copy admin kubeconfig for kubectl
        copy:
          src: "{{ playbook_dir }}/../../../configs/admin.kubeconfig"
          dest: "~"
      - name: copy controller manager config
        copy:
          src: "{{ playbook_dir }}/../../../configs/kube-controller-manager.kubeconfig"
          dest: "~"
      - name: copy scheduler config
        copy:
          src: "{{ playbook_dir }}/../../../configs/kube-scheduler.kubeconfig"
          dest: "~"